### ISSUE TITLE
Addon is greyed out

### ISSUE THREAD

**Issue by HazeOPF** [helloyanis/Infinite-craft-memorizer#1]
Steps to reproduce:
- Install addon
- Go to IC page
- Open extension bar
![2024-02-12_17-05](https://github.com/helloyanis/Infinite-craft-memorizer/assets/105099368/9af83126-5bab-4209-888d-7c0e152a6b2e)

**Comment by helloyanis** [comment]
Is this on Android or PC?
If it's on PC, the addon icon should be in the URL bar, next to the bookmark button

**Comment by HazeOPF** [comment]
Oh, I see it now. Sorry
