### ISSUE TITLE
Building all items in database adds duplicates in item list, duplicates cause search function to break the website

### ISSUE THREAD

**Issue by Prismitzi** [helloyanis/Infinite-craft-memorizer#2]
For example, the 4 default items will appear twice in the website's item list after building all items - once at the top of the list, where they always are, and then again among the alphabetically sorted items from the database. To clarify, the duplicate items only appear once in the plugin's menu. They're only duplicated on the list in the website itself.

The duplicates wouldn't be a big problem on their own, but they seem to cause a worse glitch which makes it so using the website's item search completely breaks the game until the page is refreshed. 

I don't know how to explain it in detail without writing a whole essay, but I think the most relevant thing is that building from a big enough database makes the item search pretty much completely unusable due to the add-on building items that are already in the list, including the defaults. And since there's no way in-game to delete individual items, the only way to fix it (that I'm aware of) is to reset the game entirely (which isn't a big deal thanks to this add-on btw!! super helpful, thanks for making it!!)

Steps to recreate, in case it's just a problem on my end and there's nothing to fix:

1. Reset
2. Use the add-on to create 🔥Fire, then refresh. There should be 2 Fire now, and the search function still works normally.
3. Craft Earth + Earth for Mountain
4. Typing "f" in the website's item search moves the second Fire to the front of the list, but the rest of the items aren't hidden like they should be. (Typing any other letter won't cause any problems)
5. The item list is now frozen like this even if something else is typed in the search box. New items can't be added to the crafting area. Existing items can still be moved, but behave strangely if you try to delete or duplicate them.
6. Refresh to stop the glitch.

(Note: That's only a mild example; crafting a whole database when you already have some existing items crafted pretty much locks out the entire keyboard 😅)

**Comment by helloyanis** [comment]
Thank you for the detailed steps. I've seen this happen elsewhere so it's not a problem on your end. I think this occurs because creating items doesn't check if it already exists so it creates multiple versions of the same items which the website doesn't know how to handle.
I'll take a look at it and get back to you!

**Comment by helloyanis** [comment]
I think I fixed it, can you reinstall the add-on to get the new version?
Don't forget to back up your data beforehand because uninstalling deletes the data!

**Comment by helloyanis** [comment]
I'll close this because it's fixed on my end and there's no response from you. Feel free to reopen it if you have any more problems about this.
