### ISSUE TITLE
[SUPPORT] Doesn't support mercury

### ISSUE THREAD

**Issue by xamionex** [helloyanis/Infinite-craft-memorizer#5]
When using the extension on Mercury (Firefox Fork for optimization)
The extension doesn't save anything

**Comment by xamionex** [comment]
Ah, nevermind
I just had to combine 2 items which seemed to cause the problem
I'm guessing infinite craft was uninitialized therefore the extension didn't work

**Comment by helloyanis** [comment]
Yes, the data gets initialized when you make your first fusion. Happy you solved it!
